- name: copy backend files to server
  become: true
  copy:
      src: ~/project/artifact.tar.gz
      dest: /home/ubuntu/artifact.tar.gz
- name: start npm
  shell: |
    cd /home/ubuntu
    apt update
    apt install nodejs npm
    npm install
    npm install -g pm2
    tar -xzvf artifact.tar.gz -C .
    npm run build
    pm2 completion install
    pm2 stop default
    pm2 start npm -- start