- name: copy backend files to server
  become: true
  copy:
      src: ~/project/artifact.tar.gz
      dest: /home/ubuntu/artifact.tar.gz
- name: start npm
  shell: |
    cd /home/ubuntu
    tar -xzvf artifact.tar.gz -C .
    sudo npm run build
    sudo pm2 completion install
    sudo pm2 stop default
    sudo pm2 start npm -- start