- name: copy backend files to server
  become: true
  copy:
      src: ~/project/artifact.tar.gz
      dest: /home/ubuntu/artifact.tar.gz
- name: start npm
  shell: |
    cd /home/ubuntu
    sudo apt update
    sudo apt install nodejs npms
    npm install
    npm intall pm2 -g
    tar -xzvf artifact.tar.gz -C .
    sudo apt install nodejs npm
    npm run build
    pm2 completion installl
    pm2 stop default
    pm2 start npm -- start